version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOST=${HOST}

    volumes:
      - ./uploads:/app/uploads
    ports:
      - "3005:3000"
    environment:
      - HOST=${HOST}