name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/appload:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PPYNSRVKEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "."
          target: "/opt/appload"
          
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PPYNSRVKEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /opt/appload
            export HOST=${{ secrets.HOST }}
            if [ $(docker compose ps -q | wc -l) -gt 0 ]; then
              echo "Docker Compose is up, updating services..."
              docker compose down
              docker compose build
              docker compose up -d
            fi
            else
              echo "Docker Compose is down, starting services..."
              docker compose build
              docker compose up -d
            fi
    
